---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster-webserver
  namespace: dagster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster-webserver
  template:
    metadata:
      labels:
        app: dagster-webserver
    spec:
      containers:
        - name: dagster-webserver
          image: dg-k8s:latest
          imagePullPolicy: IfNotPresent
          command: ["dagit"]
          args: ["-h", "0.0.0.0", "-p", "3000"]
          ports:
            - containerPort: 3000
          env:
            - name: DAGSTER_HOME
              value: /opt/dagster/dagster_home
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: dagster-storage
              mountPath: /opt/dagster/dagster_home
      volumes:
        - name: dagster-storage
          persistentVolumeClaim:
            claimName: dagster-storage
---
apiVersion: v1
kind: Service
metadata:
  name: dagster-webserver
  namespace: dagster
spec:
  type: NodePort
  selector:
    app: dagster-webserver
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
